language: python
sudo: false

matrix:
  include:
    - python: 3.4
      env:
        - TOX_ENV=py34
    - python: 3.5
      env:
        - TOX_ENV=py35
    - python: 3.6
      env:
        - TOX_ENV=py36

install:
  - pip install virtualenv --upgrade
  - pip install tox

script:
  - tox -e $TOX_ENV

cache:
  directories:
    - $HOME/.cache/pip
