language: python
python: 3.6
sudo: false

env:
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=py36

install:
  - pip install virtualenv --upgrade
  - pip install tox

script:
  - tox -e $TOX_ENV

cache:
  directories:
    - $HOME/.cache/pip
